name: Benchmarks

#trigger when these occur
on:
  workflow_dispatch:

#Benchmarks are currently only supported on one platform
jobs:
  run-test-cases:
    continue-on-error: true
    strategy:
      matrix:
        platforms:
          - { os: ubuntu-latest, preinstall: sudo apt-get install time }
        commands:
          - { exec: make -C tests/benchmarks -k }
    
    runs-on: ${{ matrix.platforms.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Preinstall dependencies
        run: ${{ matrix.platforms.preinstall }}
      - name: run the tests
        run: ${{ matrix.commands.exec }}
