name: Continuous Integration v1.x

#trigger when these occur
on:
  push:
    branches:
      - v1
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - v1
  workflow_dispatch:

#testing the CI workflows under multiple supported conditions
jobs:
  test-valgrind:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install valgrind
      run: sudo apt install valgrind
    - name: make test (valgrind)
      run: make test
  
  test-sanitized:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make test (sanitized)
      run: make test-sanitized
  
  test-mingw32:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: make test (mingw32)
        run: make test
