name: Standalone Tests

#trigger when these occur
on:
  workflow_dispatch:

#These tests are more stand-alone than the others
jobs:
  run-test-cases:
    continue-on-error: true
    strategy:
      matrix:
        platforms:
          - { os: ubuntu-latest, preinstall: sudo apt-get install gdb, gdb_enabled: true }
          - { os: windows-latest, preinstall: , gdb_enabled: true }
          - { os: macos-latest, preinstall: , gdb_enabled: false }
        commands:
          - { exec: make -C tests/standalone -k, gdb: false }
          - { exec: make -C tests/standalone gdb -k, gdb: true }
    
    runs-on: ${{ matrix.platforms.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Preinstall dependencies
        if: (matrix.commands.gdb == true && matrix.platforms.gdb_enabled == false) != true
        run: ${{ matrix.platforms.preinstall }}
      - name: run the tests
        if: (matrix.commands.gdb == true && matrix.platforms.gdb_enabled == false) != true
        run: ${{ matrix.commands.exec }}
