name: Comprehensive Tests, Branch "dev"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:  
  test-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Linux Test Environment
      run: |
        echo CI tests not yet implemented
